"""Added edited_by_id & edited_by  to DiscussionPost

Revision ID: 1c20c3e51d9e
Revises: 7fdb7068beda
Create Date: 2026-04-08 02:05:01.613800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c20c3e51d9e'
down_revision = '7fdb7068beda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['edited_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('edited_by_id')

    # ### end Alembic commands ###
