"""Add is_edited column to DiscussionPost

Revision ID: 7fdb7068beda
Revises: df3bc6635286
Create Date: 2026-04-08 01:52:37.435299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fdb7068beda'
down_revision = 'df3bc6635286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_edited', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion_posts', schema=None) as batch_op:
        batch_op.drop_column('is_edited')

    # ### end Alembic commands ###
